// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Promotions.gRPC.Data;

#nullable disable

namespace Promotions.gRPC.Migrations
{
    [DbContext(typeof(PromotionContext))]
    [Migration("20241105162906_Seeding")]
    partial class Seeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Promotions.gRPC.Entities.Promotion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("DiscountPercentage")
                        .HasColumnType("float");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("MaxUses")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TimesUsed")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Promotions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "Q60TY5JD",
                            Description = "Voluptatum minima assumenda explicabo odit voluptatem sit.",
                            DiscountPercentage = 12.585994345666021,
                            EndDate = new DateTime(2024, 9, 3, 2, 48, 54, 894, DateTimeKind.Local).AddTicks(8522),
                            MaxUses = 791,
                            StartDate = new DateTime(2024, 3, 7, 8, 56, 18, 49, DateTimeKind.Local).AddTicks(1096),
                            TimesUsed = 28
                        },
                        new
                        {
                            Id = 2,
                            Code = "MYUEFMHZ",
                            Description = "Id odio debitis dolor eos corporis delectus recusandae iste sit.",
                            DiscountPercentage = 11.485227270370306,
                            EndDate = new DateTime(2024, 7, 2, 1, 27, 4, 659, DateTimeKind.Local).AddTicks(9843),
                            MaxUses = 648,
                            StartDate = new DateTime(2024, 3, 28, 21, 49, 22, 93, DateTimeKind.Local).AddTicks(5813),
                            TimesUsed = 18
                        },
                        new
                        {
                            Id = 3,
                            Code = "ASGFOBZW",
                            Description = "Dolorum quia magnam quo molestiae et neque.",
                            DiscountPercentage = 31.143779386826871,
                            EndDate = new DateTime(2024, 4, 1, 20, 7, 24, 666, DateTimeKind.Local).AddTicks(509),
                            MaxUses = 493,
                            StartDate = new DateTime(2023, 11, 23, 21, 22, 27, 231, DateTimeKind.Local).AddTicks(7158),
                            TimesUsed = 15
                        },
                        new
                        {
                            Id = 4,
                            Code = "QF4LHP93",
                            Description = "Qui blanditiis distinctio est officia quia doloremque eum.",
                            DiscountPercentage = 25.637874286452192,
                            EndDate = new DateTime(2024, 6, 27, 4, 40, 2, 724, DateTimeKind.Local).AddTicks(4784),
                            MaxUses = 139,
                            StartDate = new DateTime(2024, 2, 4, 8, 50, 38, 677, DateTimeKind.Local).AddTicks(9001),
                            TimesUsed = 31
                        },
                        new
                        {
                            Id = 5,
                            Code = "X0EQZD8N",
                            Description = "Exercitationem ut molestias eum.",
                            DiscountPercentage = 16.303403936833398,
                            EndDate = new DateTime(2024, 10, 9, 9, 55, 17, 230, DateTimeKind.Local).AddTicks(5878),
                            MaxUses = 143,
                            StartDate = new DateTime(2024, 6, 20, 11, 29, 9, 453, DateTimeKind.Local).AddTicks(5759),
                            TimesUsed = 16
                        },
                        new
                        {
                            Id = 6,
                            Code = "OTEEHMQH",
                            Description = "Earum ut minima et.",
                            DiscountPercentage = 30.815199815859408,
                            EndDate = new DateTime(2024, 9, 4, 20, 50, 41, 592, DateTimeKind.Local).AddTicks(8395),
                            MaxUses = 515,
                            StartDate = new DateTime(2024, 3, 20, 13, 1, 59, 828, DateTimeKind.Local).AddTicks(4231),
                            TimesUsed = 18
                        },
                        new
                        {
                            Id = 7,
                            Code = "MIZZDPKZ",
                            Description = "Qui delectus placeat ducimus sunt suscipit consectetur voluptatibus.",
                            DiscountPercentage = 18.67677509838478,
                            EndDate = new DateTime(2025, 2, 14, 0, 15, 0, 534, DateTimeKind.Local).AddTicks(651),
                            MaxUses = 433,
                            StartDate = new DateTime(2024, 8, 26, 17, 2, 3, 584, DateTimeKind.Local).AddTicks(42),
                            TimesUsed = 14
                        },
                        new
                        {
                            Id = 8,
                            Code = "VK1XAVLF",
                            Description = "Accusantium qui a dicta fugit aspernatur et illum commodi.",
                            DiscountPercentage = 22.877655082600004,
                            EndDate = new DateTime(2024, 8, 27, 11, 11, 5, 867, DateTimeKind.Local).AddTicks(9821),
                            MaxUses = 463,
                            StartDate = new DateTime(2024, 8, 17, 23, 12, 39, 296, DateTimeKind.Local).AddTicks(2958),
                            TimesUsed = 22
                        },
                        new
                        {
                            Id = 9,
                            Code = "3D131RZH",
                            Description = "Odio eos quis quia sed.",
                            DiscountPercentage = 46.738922225829583,
                            EndDate = new DateTime(2024, 10, 28, 9, 18, 39, 681, DateTimeKind.Local).AddTicks(1113),
                            MaxUses = 161,
                            StartDate = new DateTime(2024, 6, 25, 7, 22, 49, 871, DateTimeKind.Local).AddTicks(8059),
                            TimesUsed = 49
                        },
                        new
                        {
                            Id = 10,
                            Code = "RBUVNMTT",
                            Description = "Consequatur quaerat aut explicabo quidem magnam delectus vel nulla.",
                            DiscountPercentage = 5.0519861289140513,
                            EndDate = new DateTime(2025, 1, 29, 0, 46, 18, 84, DateTimeKind.Local).AddTicks(653),
                            MaxUses = 843,
                            StartDate = new DateTime(2024, 9, 18, 4, 39, 49, 508, DateTimeKind.Local).AddTicks(30),
                            TimesUsed = 17
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
